Document: zfsnap
Title: Debian zfsnap Manual
Author: <insert document author here>
Abstract: This manual describes what zfsnap is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/zfsnap/zfsnap.sgml.gz

Format: postscript
Files: /usr/share/doc/zfsnap/zfsnap.ps.gz

Format: text
Files: /usr/share/doc/zfsnap/zfsnap.text.gz

Format: HTML
Index: /usr/share/doc/zfsnap/html/index.html
Files: /usr/share/doc/zfsnap/html/*.html
